---
- name: create asb-client token secret
  oc_obj:
    name: asb-client
    namespace: openshift-ansible-service-broker
    state: present
    kind: Secret
    content:
      path: /tmp/asbclientsecretout
      data:
        apiVersion: v1
        kind: Secret
        metadata:
          name: asb-client
          namespace: openshift-ansible-service-broker
          annotations:
            kubernetes.io/service-account.name: asb-client
        type: kubernetes.io/service-account-token

- oc_secret:
    state: list
    namespace: openshift-ansible-service-broker
    name: asb-client
  register: asb_client_secret

- set_fact:
    service_ca_crt: "{{ asb_client_secret.results.results.0.data['service-ca.crt'] }}"

- name: Create etcd-auth secret
  oc_secret:
    name: etcd-auth-secret
    namespace: openshift-ansible-service-broker
    contents:
      - path: ca.crt
        data: '{{ etcd_ca_cert }}'

- name: Create broker-etcd-auth secret
  oc_secret:
    name: broker-etcd-auth-secret
    namespace: openshift-ansible-service-broker
    contents:
      - path: client.crt
        data: '{{ etcd_client_cert }}'
      - path: client.key
        data: '{{ etcd_client_key }}'

# The annotation would create asb-tls secret
- name: create ansible-service-broker service
  oc_service:
    name: asb
    namespace: openshift-ansible-service-broker
    labels:
      app: openshift-ansible-service-broker
      service: asb
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: asb-tls
    ports:
      - name: port-1338
        port: 1338
        targetPort: 1338
        protocol: TCP
    selector:
      app: openshift-ansible-service-broker
      service: asb

# The annotation would create etcd-tls secret
- name: create asb-etcd service
  oc_service:
    name: asb-etcd
    namespace: openshift-ansible-service-broker
    labels:
      app: etcd
      service: asb-etcd
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: etcd-tls
    ports:
      - name: port-2379
        port: 2379
        targetPort: 2379
        protocol: TCP
    selector:
      app: etcd
      service: asb-etcd
