apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs/volumes
    server: 10.19.0.216
  persistentVolumeReclaimPolicy: Recycle
