---
- name: Delete existing secrets
  oc_secret:
    name: "{{ item }}"
    namespace: openshift-ansible-service-broker
    state: absent
  with_items:
    - etcd-auth-secret
    - broker-etcd-auth-secret
    - asb-client
    - asb-tls
    - etcd-tls

- name: Delete master certs
  file:
    path: "{{ openshift.common.config_base }}/ansible-service-broker/{{ item }}"
    state: absent
  with_items:
    - cert.pem
    - client.key
    - client.csr
    - client.pem
