---
- name: install needed rpm(s)
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ r_openshift_node_image_prep_packages }}"
  register: result
  until: result is succeeded
  when: not (openshift_is_atomic | default(False) | bool)

- name: install SDN package
  package:
    name: "{{ openshift_service_type }}-sdn-ovs"
    state: present
  when: openshift_use_openshift_sdn | default(true) | bool
  register: result
  until: result | success
