apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudforms
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs/volumes-app
    server: 10.19.0.216
  persistentVolumeReclaimPolicy: Recycle
