#!/bin/bash

MYIP=$(ifconfig ens33 | grep inet | head -n 1 | awk '{print $2}')
sed -i "s/127\.0\.0\.1/$MYIP/g" /etc/hosts

# core packages
dnf install -y wget git net-tools bind-utils yum-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct


# update packages
dnf update -y
systemctl reboot


