apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfme-pv02
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/cfme-pv02
    server: <your-nfs-host-here>
  persistentVolumeReclaimPolicy: Retain
